version: '3.3'
services:
  db:
    image: postgres:14.5
    container_name: postgres_adlchemy
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=adlchemydb
    volumes:
      - "c:/pg_data:/var/lib/postgresql/data"

